spring.application.name=MicroFinanceSoftware
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:mysql://103.38.50.113:3306/microfinanceDB
#spring.datasource.url=jdbc:mysql://localhost:3306/microfinanceDB

#kamke.in server db
#MYSQL CONFIG ONLINE SERVER
#10.10.20.166
#MYSQL CONFIG OFFLINE SERVER
#103.30.72.166

#spring.datasource.url=jdbc:mysql://103.30.72.166:8012/microfinanceDB
#spring.datasource.username=root
#spring.datasource.password=1MZcfaG+?#5U2]4ZU&



spring.datasource.username=infosai
spring.datasource.password=Infosai@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#spring.datasource.password=admin@123456789

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect


#upload.directory=D:/MicroFinancsSoftware/MicroFinanceSoftware/src/main/webapp/Uploads

#upload.directory=G:/MicroFinanceSoftware/src/main/webapp/Uploads

#upload.directory=/usr/local/tomcat9/webapps/Microfinance/Uploads






#upload.directory=E:/BuilderProject/microfinancsoftware/MicroFinanceSoftware/src/main/webapp/Uploads




#upload.directory=E:/MicroFinance/MicroFinanceSoftware/srcmain/webapp/Uploads
#upload.directory=D:/MicroFinanceSoftware/MicroFinanceSoftware/src/main/webapp/Uploads


#upload.directory=D:/Microfinance/MicroFinanceSoftware/src/main/webapp/Uploads




#upload.directory=D:/Microfinance/MicroFinanceSoftware/src/main/webapp/Uploads


#upload.directory=D:/MicroFinanceSoftware/MicroFinanceSoftware/src/main/webapp/Uploads

#upload.directory=D:/MicroFinanceSoftware/MicroFinanceSoftware/src/main/webapp/Uploads


#upload.directory=D:/MicroFinanceSoftware/MicroFinanceSoftware/src/main/webapp/Uploads




#upload.directory=D:/INFOSAISOFTWARE/MicroFinanceSoftware/src/main/webapp/Uploads


#upload.directory=D:/INFOSAISOFTWARE/MicroFinanceSoftware/src/main/webapp/Uploads


#upload.directory=D:/MicroFinanceSoftware/MicroFinanceSoftware/src/main/webapp/Uploads

#upload.directory=D:/MicroFinanceSoftware/MicroFinanceSoftware/src/main/webapp/Uploads



#upload.directory=D:/MicroFinanceSoftware/MicroFinanceSoftware/src/main/webapp/Uploads


#upload.directory=D:/MicroFinanceSoftware/MicroFinanceSoftware/src/main/webapp/Uploads






#upload.directory=D:/MicroFinanceSoftware/MicroFinanceSoftware/src/main/webapp/Uploads


#upload.directory=C:/Infosai_project_clone/MicroFinanceSoftware/src/main/webapp/Uploads





#upload.directory=C:\\Infosai_project_clone\\MicroFinanceSoftware\\src\\main\\webapp\\Uploads

#upload.directory=E:/BuilderProject/microfinancsoftware/MicroFinanceSoftware/src/main/webapp/Uploads



#upload.directory=E:/BuilderProject/microfinancsoftware/MicroFinanceSoftware/src/main/webapp/Uploads

#upload.directory=D:/MicroFinancsSoftware/MicroFinanceSoftware/src/main/webapp/Uploads





#upload.directory=D:/MicroFinancsSoftware/MicroFinanceSoftware/src/main/webapp/Uploads



#upload.directory=D:/microfinancesoftware/MicroFinanceSoftware/src/main/webapp/Uploads

#upload.directory=D:/Infosai Projects/Microfinance/MicroFinanceSoftware/src/main/webapp/Uploads





#upload.directory=E:/BuilderProject/microfinancsoftware/MicroFinanceSoftware/src/main/webapp/Uploads



#upload.directory=E:/BuilderProject/microfinancsoftware/MicroFinanceSoftware/src/main/webapp/Uploads



#upload.directory=C:\\Infosai_project_clone\\MicroFinanceSoftware\\src\\main\\webapp\\Uploads




upload.directory=E:/BuilderProject/microfinancsoftware/MicroFinanceSoftware/src/main/webapp/Uploads

#upload.directory=C:\\Infosai_project_clone\\MicroFinanceSoftware\\src\\main\\webapp\\Uploads

