spring.application.name=MicroFinanceSoftware
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://103.38.50.113:3306/microfinanceDB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=infosai
spring.datasource.password=Infosai@1234
=======
spring.datasource.url=jdbc:mysql://localhost:3306/microfinancedb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Admin@555
>>>>>>> 3fd3afd3695257db684c438722ac0a343f53ce55
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

file.upload-dir=uploads/