spring.application.name=MicroFinanceSoftware
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:mysql://103.38.50.113:3306/microfinanceDB
<<<<<<< HEAD

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.username=infosai
spring.datasource.password=Infosai@1234
=======
#spring.datasource.url=jdbc:mysql://localhost:3306/microfinancedb

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.datasource.username=root
#spring.datasource.password=admin@123456789
spring.datasource.username=infosai
#spring.datasource.username=root
spring.datasource.password=Infosai@1234
#spring.datasource.password=Admin@555
#spring.datasource.username=root
#spring.datasource.password=admin@123456789
>>>>>>> e3773a7de865847a8e8e075ec8c9439c2869a181

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

<<<<<<< HEAD
server.port=8081
#upload.directory=D:/MicroFinanceSoftware/MicroFinanceSoftware/src/main/webapp/Uploads

upload.directory=E:/BuilderProject/microfinancsoftware/MicroFinanceSoftware/src/main/webapp/Uploads

=======
upload.directory=E:/MicroFinance/MicroFinanceSoftware/src/main/webapp/Uploads
>>>>>>> e3773a7de865847a8e8e075ec8c9439c2869a181

